# Generated by Django 6.0.6 on 2026-06-05 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('year', models.PositiveIntegerField()),
                ('host_country', models.CharField(blank=True, max_length=100)),
                ('tournament_type', models.CharField(choices=[('world_cup', 'World Cup'), ('qualifiers', 'Qualifiers'), ('friendly', 'Friendly')], default='world_cup', max_length=20)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-year', 'name'],
                'unique_together': {('name', 'year')},
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('group', 'Group Stage'), ('round_32', 'Round of 32'), ('round_16', 'Round of 16'), ('quarterfinal', 'Quarterfinal'), ('semifinal', 'Semifinal'), ('third_place', 'Third Place'), ('final', 'Final')], max_length=20)),
                ('group', models.CharField(blank=True, max_length=1)),
                ('match_date', models.DateTimeField()),
                ('stadium', models.CharField(blank=True, max_length=120)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('live', 'Live'), ('finished', 'Finished'), ('postponed', 'Postponed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('home_score', models.PositiveIntegerField(default=0)),
                ('away_score', models.PositiveIntegerField(default=0)),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_matches', to='teams.team')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_matches', to='teams.team')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='matches.tournament')),
            ],
            options={
                'ordering': ['match_date'],
            },
        ),
    ]
