# Generated by Django 6.0.4 on 2026-06-05 20:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0001_initial'),
        ('players', '0001_initial'),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minute', models.PositiveIntegerField()),
                ('extra_minute', models.PositiveIntegerField(blank=True, null=True)),
                ('event_type', models.CharField(choices=[('goal', 'Goal'), ('own_goal', 'Own Goal'), ('penalty_goal', 'Penalty Goal'), ('missed_penalty', 'Missed Penalty'), ('yellow_card', 'Yellow Card'), ('red_card', 'Red Card'), ('second_yellow_red', 'Second Yellow Red'), ('substitution', 'Substitution'), ('var', 'VAR Review'), ('injury', 'Injury'), ('other', 'Other')], max_length=30)),
                ('title', models.CharField(blank=True, max_length=150)),
                ('description', models.TextField(blank=True)),
                ('is_key_event', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='matches.match')),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='match_events', to='players.player')),
                ('related_player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_match_events', to='players.player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_events', to='teams.team')),
            ],
            options={
                'ordering': ['minute', 'extra_minute', 'id'],
            },
        ),
    ]
