# Generated by Django 6.0.4 on 2026-06-05 21:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0002_matchevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('summary', models.TextField(blank=True)),
                ('key_points', models.TextField(blank=True)),
                ('tactical_notes', models.TextField(blank=True)),
                ('generated_at', models.DateTimeField(auto_now=True)),
                ('is_auto_generated', models.BooleanField(default=True)),
                ('match', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='matches.match')),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
    ]
