# Generated by Django 6.0.4 on 2026-06-05 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0003_matchreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchreport',
            name='ai_headline',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='matchreport',
            name='ai_key_takeaways',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='matchreport',
            name='ai_summary',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='matchreport',
            name='ai_tactical_reading',
            field=models.TextField(blank=True),
        ),
    ]
