# Generated by Django 6.0.6 on 2026-06-05 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('fifa_code', models.CharField(max_length=3, unique=True)),
                ('confederation', models.CharField(choices=[('UEFA', 'UEFA'), ('CONMEBOL', 'CONMEBOL'), ('CONCACAF', 'CONCACAF'), ('CAF', 'CAF'), ('AFC', 'AFC'), ('OFC', 'OFC')], max_length=10)),
                ('coach', models.CharField(blank=True, max_length=100)),
                ('fifa_ranking', models.PositiveIntegerField(blank=True, null=True)),
                ('group', models.CharField(blank=True, max_length=1)),
                ('primary_color', models.CharField(blank=True, max_length=7)),
                ('secondary_color', models.CharField(blank=True, max_length=7)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
