# Generated by Django 6.0.4 on 2026-06-05 22:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('summary', models.TextField(blank=True)),
                ('performance_overview', models.TextField(blank=True)),
                ('squad_notes', models.TextField(blank=True)),
                ('discipline_notes', models.TextField(blank=True)),
                ('generated_at', models.DateTimeField(auto_now=True)),
                ('is_auto_generated', models.BooleanField(default=True)),
                ('team', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='teams.team')),
            ],
            options={
                'ordering': ['team__name'],
            },
        ),
    ]
