# Generated by Django 6.0.4 on 2026-06-05 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_teamreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamreport',
            name='ai_headline',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='teamreport',
            name='ai_priority_alerts',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='teamreport',
            name='ai_summary',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='teamreport',
            name='ai_tactical_profile',
            field=models.TextField(blank=True),
        ),
    ]
