# Generated by Django 6.0.6 on 2026-06-06 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_teamreport_ai_headline_teamreport_ai_priority_alerts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='external_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
