FIFA_TO_FLAG_CODE = {
    "ALG": "dz",
    "ARG": "ar",
    "AUS": "au",
    "AUT": "at",
    "BEL": "be",
    "BIH": "ba",
    "BRA": "br",
    "CAN": "ca",
    "CHI": "cl",
    "CMR": "cm",
    "COD": "cd",
    "COL": "co",
    "CPV": "cv",
    "CRC": "cr",
    "CRO": "hr",
    "CUW": "cw",
    "CZE": "cz",
    "DEN": "dk",
    "ECU": "ec",
    "EGY": "eg",
    "ENG": "gb-eng",
    "ESP": "es",
    "FRA": "fr",
    "GHA": "gh",
    "GRE": "gr",
    "HAI": "ht",
    "HON": "hn",
    "IRN": "ir",
    "IRQ": "iq",
    "ISL": "is",
    "ITA": "it",
    "JAM": "jm",
    "JOR": "jo",
    "JPN": "jp",
    "KOR": "kr",
    "KSA": "sa",
    "MAR": "ma",
    "MEX": "mx",
    "NED": "nl",
    "NGA": "ng",
    "NOR": "no",
    "NZL": "nz",
    "PAN": "pa",
    "PAR": "py",
    "PER": "pe",
    "POL": "pl",
    "POR": "pt",
    "QAT": "qa",
    "ROU": "ro",
    "RSA": "za",
    "SCO": "gb-sct",
    "SEN": "sn",
    "SRB": "rs",
    "SUI": "ch",
    "SWE": "se",
    "TUN": "tn",
    "TUR": "tr",
    "UKR": "ua",
    "URU": "uy",
    "USA": "us",
    "UZB": "uz",
    "VEN": "ve",
    "WAL": "gb-wls",
}

TEAM_NAME_TO_FLAG_CODE = {
    "algeria": "dz",
    "argentina": "ar",
    "australia": "au",
    "austria": "at",
    "belgium": "be",
    "bosnia and herzegovina": "ba",
    "brazil": "br",
    "canada": "ca",
    "cape verde": "cv",
    "chile": "cl",
    "colombia": "co",
    "congo dr": "cd",
    "costa rica": "cr",
    "croatia": "hr",
    "curaçao": "cw",
    "curacao": "cw",
    "czech republic": "cz",
    "czechia": "cz",
    "democratic republic of congo": "cd",
    "democratic republic of the congo": "cd",
    "denmark": "dk",
    "dr congo": "cd",
    "ecuador": "ec",
    "egypt": "eg",
    "england": "gb-eng",
    "france": "fr",
    "germany": "de",
    "ghana": "gh",
    "greece": "gr",
    "haiti": "ht",
    "honduras": "hn",
    "iceland": "is",
    "iran": "ir",
    "iraq": "iq",
    "italy": "it",
    "jamaica": "jm",
    "japan": "jp",
    "jordan": "jo",
    "korea republic": "kr",
    "mexico": "mx",
    "morocco": "ma",
    "netherlands": "nl",
    "new zealand": "nz",
    "nigeria": "ng",
    "norway": "no",
    "panama": "pa",
    "paraguay": "py",
    "peru": "pe",
    "poland": "pl",
    "portugal": "pt",
    "qatar": "qa",
    "romania": "ro",
    "saudi arabia": "sa",
    "scotland": "gb-sct",
    "senegal": "sn",
    "serbia": "rs",
    "south africa": "za",
    "spain": "es",
    "sweden": "se",
    "switzerland": "ch",
    "tunisia": "tn",
    "turkey": "tr",
    "ukraine": "ua",
    "united states": "us",
    "uruguay": "uy",
    "uzbekistan": "uz",
    "venezuela": "ve",
    "wales": "gb-wls",
}   


def get_flag_code(team):
    fifa_code = (getattr(team, "fifa_code", "") or "").strip().upper()
    name = (getattr(team, "name", "") or "").strip().lower()

    if fifa_code in FIFA_TO_FLAG_CODE:
        return FIFA_TO_FLAG_CODE[fifa_code]

    if name in TEAM_NAME_TO_FLAG_CODE:
        return TEAM_NAME_TO_FLAG_CODE[name]

    return None