# Generated by Django 6.0.6 on 2026-06-07 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_player_external_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='caps',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='height_cm',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='international_goals',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='preferred_foot',
            field=models.CharField(blank=True, choices=[('right', 'Right'), ('left', 'Left'), ('both', 'Both')], max_length=10),
        ),
    ]
